name: cards_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #? Localization
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  logger: ^2.0.1
  provider: ^6.0.5
  file_picker: ^5.5.0
  lottie: ^2.6.0
  shimmer: ^3.0.0
  flutter_screenutil: ^5.3.1
  http: ^0.13.4
  google_fonts:
  gap: ^3.0.1
  flutter_hooks:
  another_flushbar:
  blur: ^3.1.0
  dotted_border: ^2.0.0+3
  permission_handler: ^11.0.0
  fast_cached_network_image: ^1.2.0

  #? Injector
  get_it: ^7.6.4

  #? Hive
  hive: ^2.2.3
  hive_flutter:
  url_launcher: ^6.1.14

  #? Injector
  get_it: ^7.6.4

  #? Drawer
  flutter_slider_drawer: ^2.1.3

  #? Local Storage
  get_storage: ^2.1.1

  #? slider
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/
flutter_intl:
  enabled: true